version: '3.8'

services:
  auth-service:
    image: ngochoa203/pathlight-auth-service:latest
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - ../.env
    networks:
      - pathlight-network

  course-service:
    image: ngochoa203/pathlight-course-service:latest
    ports:
      - "${COURSE_SERVICE_PORT}:${COURSE_SERVICE_PORT}"
    env_file:
      - ../.env
    networks:
      - pathlight-network

  quiz-service:
    image: ngochoa203/pathlight-quiz-service:latest
    ports:
      - "${QUIZ_SERVICE_PORT}:${QUIZ_SERVICE_PORT}"
    env_file:
      - ../.env
    networks:
      - pathlight-network

  user-service:
    image: ngochoa203/pathlight-user-service:latest
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file:
      - ../.env
    networks:
      - pathlight-network

networks:
  pathlight-network:
    driver: bridge
