# Agentic Service CI/CD Configuration

name: agentic-service
version: 1.0.0

# Environment-specific configurations
environments:
  dev:
    aws_region: us-east-1
    memory_size: 1024
    timeout: 300
    log_level: DEBUG
  
  staging:
    aws_region: us-east-1
    memory_size: 2048
    timeout: 600
    log_level: INFO
  
  prod:
    aws_region: us-east-1
    memory_size: 3008
    timeout: 900
    log_level: WARNING

# Docker configuration
docker:
  python_version: "3.12"
  base_image: "public.ecr.aws/lambda/python:3.12"

# Security scanning
security:
  enable_vulnerability_scan: true
  enable_code_quality_scan: true
  fail_on_high_severity: false  # Set to true for stricter security

# Testing configuration
testing:
  enable_unit_tests: true
  enable_integration_tests: true
  coverage_threshold: 80

# Deployment configuration
deployment:
  enable_canary: false  # Enable for production canary deployments
  rollback_on_failure: true
  health_check_retries: 3
  health_check_timeout: 30
