version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - ../../.env
    volumes:
      - .:/app
    command: /opt/venv/bin/python -m uvicorn src.main:app --host 0.0.0.0 --port ${AUTH_SERVICE_PORT} --reload
    networks:
      - pathlight-network

networks:
  pathlight-network:
    driver: bridge
