[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quiz-service"
version = "0.1.0" 
description = "Quiz management service for PathLight"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "sqlalchemy>=2.0.0",
    "alembic>=1.13.0",
    "psycopg2-binary>=2.9.0",
    "python-dotenv>=1.0.0",
    "python-multipart>=0.0.6",
    "httpx>=0.25.0",
]

[tool.hatchling.build.targets.wheel]
packages = ["src/quiz_service"]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "httpx>=0.25.0",
]
